server:
  port: 1337
spring:
  application:
    name: pip-server
  ai:
    ollama:
      chat:
        options:
          model: qwen3:8b
    mcp:
      client:
        enabled: true
        toolcallback:
          enabled: true
        stdio:
          connections:
            mcpip:
              command: java
              args:
                - -jar
                - target/mcpip-1.0.0.jar
              env:
                SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
                SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
                SPOTIFY_REFRESH_TOKEN: ${SPOTIFY_REFRESH_TOKEN}
                SAVE_DIRECTORY: ${SAVE_DIRECTORY}
#          servers-configuration: classpath:mcp-servers-example.json

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: INFO