server:
  port: 1337
spring:
  application:
    name: pip-server
  ai:
    ollama:
      chat:
        options:
          model: qwen3:8b
    mcp:
      client:
        enabled: true
        toolcallback:
          enabled: true
        stdio:
          servers-configuration: classpath:mcp-servers.json

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: INFO